CREATE TABLE IF NOT EXISTS EMPLOYEES (
   EMPLOYEES_NO VARCHAR(20) PRIMARY KEY,
   NAME TEXT NOT NULL,
   SALARY TEXT,
   PHONE TEXT,
   HOURS_WORKED INTEGER
);
INSERT INTO EMPLOYEES (EMPLOYEES_NO, NAME, SALARY, PHONE, HOURS_WORKED) VALUES
  ('1', 'MUHAMMAD', '45000', '*****', 7),
  ('2', 'NOUMAN', '50000', '*****', 8),
  ('3', 'BABAR', '75000', '*****', 6),
  ('4', 'IMAD', '50000', '*****', 8),
  ('5', 'FAISAL', '60000', '*****',8.5),
  ('6', 'KAMRAN', '60000', '*****', 8.5);
SELECT AVG(SALARY) AS Average_salary
FROM EMPLOYEES;
SELECT SUM(SALARY) AS Total_salary
FROM EMPLOYEES;